# -*- coding: utf-8 -*-
"""Corrector_OrtograficoV0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/113agKej1yNidF2m6_2RVRfZirmU-A2YC

**Módulo Revisor ortográfico**

**Implementación:** Jonathan Alexander Torres Benítez

**Fecha:** 15/11/2021
"""

pip install -U textblob

pip install -U autocorrect

pip install -U pyspellchecker

pip install -U pattern

# Importación de biblioteca
from spellchecker import SpellChecker

dir(SpellChecker)

# Cargar lista de frecuencia de palabras por defecto
spell = SpellChecker(language='es')

spell.word_frequency.load_words('necesidad')

#Aquí debe recibir el tweet y separarlo palabra por palabra en un arreglo
tweetDoc = ["habrir", "alla", "nesecidad", "ablando", "ifla", "rempalago"]

"""# **Corrección de palabras**"""

for filtroPalabra in tweetDoc:
  print(f'{filtroPalabra}:{spell.correction(filtroPalabra)}')

"""#**Candidatos sugeridos**"""

for filtroPalabra in tweetDoc:
  print(f'{filtroPalabra}:{spell.candidates(filtroPalabra)}')

"""**La frecuencia de la palabra dada fuera de todas las palabras en la lista de frecuencia**"""

for filtroPalabra in tweetDoc:
  print(f'{filtroPalabra}:{spell.correction(filtroPalabra)}:probabilidad {spell.word_usage_frequency(filtroPalabra)}')

"""**Agregando o actualizando la frecuencia de palabras**


*   Agregamos nuestra lista de palabras como un archivo txt.
    * .word_frequency.load_text_file()

*   O agregamos las palabras directamente
    * .word_frequency.load_words()


"""

miNombre = "cocholate"

spell.correction(miNombre)

spell.candidates(miNombre)

# Cargar lista de frecuencia de palabras por defecto y agregar una nueva lista de palabras .txt
new_spell = SpellChecker()

new_spell.word_frequency.load_text_file("/content/1000_formas.TXT") #cambiar el archivo

"""# **Corrección de palabras**"""

#Aquí debe recibir el tweet y separarlo palabra por palabra en un arreglo
tweetDoc = ["habrir", "haser", "ambre", "siftware", "filla", "frma"]

for filtroPalabra in tweetDoc:
  print(f'{filtroPalabra}:{new_spell.correction(filtroPalabra)}')

new_spell.correction(miNombre)

new_spell.candidates(miNombre)

new_spell.word_frequency.load_words(["uribe"])

new_spell.correction(miNombre)

new_spell.candidates(miNombre)

"""**Pseudocódigo de notificador de errores**"""

for palabra in miNombre: #miNombre es el tweet
  if miNombre != new_spell.correction(miNombre):
    print({miNombre}, "puntuación +1 de que es una fake new")
      contadorDeError 
    else:
      contadorDeAciertos
      print("La semántica es ")

"""#Pruebas"""

# Probando nuestra nueva word_frequency
spell.word_frequency.load_words(['Anakin', 'Azane', 'Demiha', 'Falija', 'necesidad'])

spell.correction('nesecidad')

spell.candidates('nesecidad')

spell.correction('carles')

"""**Evitar que ciertas palabras se marquen como mal escritas**

# **Autocorrect**
"""

#Load Pkg
from autocorrect import Speller

tweetDoc

spellsan = Speller('es')

for tweetDoc in tweetDoc:
  print(spellsan(tweetDoc))

"""# **Texblob**


*   pip install textblob
*   Word.SpellCheck
*   Correct


"""

# Cargando los paquetes
from textblob import TextBlob, Word
import nltk

nltk.download('punkt')

ejemplo = TextBlob("Esto es una nueba colexión")

for filtroPalabra in ejemplo.words:
  print(filtroPalabra, ":", filtroPalabra.correct())