# -*- coding: utf-8 -*-
"""Modulo_ LeerTweets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzrBhke2rR7yOty6BIkQXhsHS-Crl7EH

##**MÓDULO APIS DE TWITTER**
"""

import tweepy
import json

# Claves de autenticación de nuestra app para usar las APIs de Twitter
api_key = '9EKMeo5s9gREJTapdzB5p8bso'
api_key_secret = 'U86aINaN6gVN8NQnkgVzyPtoKwlUAT4EkS3exSKB0ZqkVZ7wDj'
access_token = '1456247739101155333-9MvzSVvmcd090VMOk4eS4Rjib1k18j'
access_token_secret = 'foghuWBWFtXm2Tr8mW2ueosrmpzhvXzgAMMHcqMiN109v'

auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify= True)

class TweetsListener(tweepy.StreamListener):
  def on_connect(self):
    print("Conectado!!!")

  def on_data(self,tweet):
    jsonTweet = json.loads(tweet)
    id_tweet = jsonTweet['in_reply_to_status_id_str']
    noticia = api.get_oembed('https://twitter.com/id/status/'+id_tweet)
    #texto = api.search(noticia["url"])
    texto = api.search(id_tweet)
    
    #texto = api.get_oembed('https://twitter.com/id/status/'+id_tweet) 
    print(f"El texto es : {texto}")
    try: 
      texto = texto[0]._json
    except:
      print("Tweet no disponible ")
    print("TWEET ORIGINAL",json.dumps(jsonTweet, indent=2))
    print("TWEET DE LA NOTICIA", json.dumps( texto, indent=2))
    text = ""
    #api.retweet(texto["quoted_status"]["id_str"])
    try:
      text = texto['quoted_status']['text']
    except:
      try:
        text = texto['retweeted_status']['text']
      except:
        text = texto['text']
    api.update_status("La siguiente noticia se está analizando.\n"+noticia['url']) 
  def on_status(self, status):
    print(status.text)
  def on_error(self, status_code):
    print("Error", status_code)

stream = TweetsListener()
streamingApi = tweepy.Stream(auth=api.auth, listener=stream)

# Parámetro follow para filtrar por listas de ids de usuarios
# Párametro track para lista de palabras clave
streamingApi.filter(
    track=["@AntiFakeColo"]
)

